#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinSurprise.Resource", IsApplication=true)]

namespace XamarinSurprise
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int BtnAllow = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int BtnDeny = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int BtnSkip = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int BtnWatch = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int TxtvInfo = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout2 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04001d
			public const int action_sign_in = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int action_sign_in_short = 2130968606;
			
			// aapt resource value: 0x7f040016
			public const int allow_action = 2130968598;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int btBarcode_login = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int btClose_main = 2130968582;
			
			// aapt resource value: 0x7f04000e
			public const int btHistory_menu = 2130968590;
			
			// aapt resource value: 0x7f040005
			public const int btInfo_main = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int btLogin_login = 2130968584;
			
			// aapt resource value: 0x7f040010
			public const int btLogout_menu = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int btPause_menu = 2130968591;
			
			// aapt resource value: 0x7f040004
			public const int btPin_main = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int btStart_main = 2130968579;
			
			// aapt resource value: 0x7f040017
			public const int cancel_action = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int check_action = 2130968600;
			
			// aapt resource value: 0x7f040022
			public const int error_field_required = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int error_incorrect_password = 2130968609;
			
			// aapt resource value: 0x7f04001f
			public const int error_invalid_email = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int error_invalid_password = 2130968608;
			
			// aapt resource value: 0x7f040025
			public const int infoText = 2130968613;
			
			// aapt resource value: 0x7f04000b
			public const int lbInfo_login = 2130968587;
			
			// aapt resource value: 0x7f040014
			public const int log_token = 2130968596;
			
			// aapt resource value: 0x7f040026
			public const int madeBy = 2130968614;
			
			// aapt resource value: 0x7f040011
			public const int msg_subscribed = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int msg_token_fmt = 2130968594;
			
			// aapt resource value: 0x7f040023
			public const int permission_rationale = 2130968611;
			
			// aapt resource value: 0x7f04001b
			public const int prompt_email = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int prompt_password = 2130968604;
			
			// aapt resource value: 0x7f040015
			public const int quickstart_message = 2130968597;
			
			// aapt resource value: 0x7f040019
			public const int skip_action = 2130968601;
			
			// aapt resource value: 0x7f040013
			public const int subscribe_to_news = 2130968595;
			
			// aapt resource value: 0x7f04000d
			public const int tStatus_menu = 2130968589;
			
			// aapt resource value: 0x7f040001
			public const int tTitle_main = 2130968577;
			
			// aapt resource value: 0x7f04000c
			public const int tTitle_menu = 2130968588;
			
			// aapt resource value: 0x7f04001a
			public const int title_activity_login_activitytesto = 2130968602;
			
			// aapt resource value: 0x7f040002
			public const int tsubTitle = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int txtPassword_login = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int txtUsername_login = 2130968585;
			
			// aapt resource value: 0x7f040024
			public const int versionText = 2130968612;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
